<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-10-17T11:16:47 IST" name="All Test Suite" finished-at="2023-10-17T11:17:03 IST" duration-ms="16167">
    <groups>
    </groups>
    <test started-at="2023-10-17T11:16:47 IST" name="Tutninja" finished-at="2023-10-17T11:17:03 IST" duration-ms="16167">
      <class name="TestCases.LoginTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:TestCases.LoginTest@4387b79e]" started-at="2023-10-17T11:16:47 IST" name="setup" finished-at="2023-10-17T11:16:52 IST" duration-ms="5126" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="Login_with_valid_details()[pri:1, instance:TestCases.LoginTest@4387b79e]" started-at="2023-10-17T11:16:52 IST" name="Login_with_valid_details" finished-at="2023-10-17T11:16:53 IST" duration-ms="983" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[not login corretly expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: not login corretly expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertFalse(Assert.java:79)
at TestCases.LoginTest.Login_with_valid_details(LoginTest.java:49)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_with_valid_details -->
        <test-method is-config="true" signature="Teardown()[pri:0, instance:TestCases.LoginTest@4387b79e]" started-at="2023-10-17T11:16:53 IST" name="Teardown" finished-at="2023-10-17T11:16:53 IST" duration-ms="243" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Teardown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:TestCases.LoginTest@4387b79e]" started-at="2023-10-17T11:16:53 IST" name="setup" finished-at="2023-10-17T11:16:57 IST" duration-ms="3868" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="Login_with_INvalid_details()[pri:2, instance:TestCases.LoginTest@4387b79e]" started-at="2023-10-17T11:16:57 IST" name="Login_with_INvalid_details" finished-at="2023-10-17T11:16:58 IST" duration-ms="841" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_with_INvalid_details -->
        <test-method is-config="true" signature="Teardown()[pri:0, instance:TestCases.LoginTest@4387b79e]" started-at="2023-10-17T11:16:58 IST" name="Teardown" finished-at="2023-10-17T11:16:58 IST" duration-ms="194" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Teardown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:TestCases.LoginTest@4387b79e]" started-at="2023-10-17T11:16:58 IST" name="setup" finished-at="2023-10-17T11:17:02 IST" duration-ms="3982" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="Login_With_no_data()[pri:3, instance:TestCases.LoginTest@4387b79e]" started-at="2023-10-17T11:17:02 IST" name="Login_With_no_data" finished-at="2023-10-17T11:17:03 IST" duration-ms="646" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_With_no_data -->
        <test-method is-config="true" signature="Teardown()[pri:0, instance:TestCases.LoginTest@4387b79e]" started-at="2023-10-17T11:17:03 IST" name="Teardown" finished-at="2023-10-17T11:17:03 IST" duration-ms="209" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Teardown -->
      </class> <!-- TestCases.LoginTest -->
    </test> <!-- Tutninja -->
  </suite> <!-- All Test Suite -->
</testng-results>
